# Generated by Django 4.2.4 on 2023-09-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=32)),
                ('job_level', models.CharField(choices=[('EN', 'ENTRY'), ('JU', 'JUNIOR'), ('SE', 'SENIOR+')], max_length=2)),
                ('job_hirer', models.CharField(max_length=32)),
                ('job_location', models.CharField(max_length=32)),
                ('job_salary', models.IntegerField()),
            ],
        ),
    ]
