# Generated by Django 4.2.4 on 2023-09-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0004_job_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_skills',
            field=models.TextField(null=True),
        ),
    ]
