# Generated by Django 4.2.4 on 2023-09-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0005_job_job_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
