# Generated by Django 4.2.4 on 2023-09-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0007_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_resume',
            field=models.FileField(default='defaults/default_resume.txt', upload_to='application_resumes/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='target_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appplications_to_job', to='jobsearch.job'),
        ),
    ]
