# Generated by Django 4.2.4 on 2023-09-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobsearch', '0012_alter_job_job_hirer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hirer',
        ),
        migrations.AddField(
            model_name='job',
            name='job_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
