# Generated by Django 4.2.4 on 2023-09-13 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobsearch', '0013_delete_hirer_job_job_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_creator',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_skills',
        ),
    ]
