name: JobexchangeApp Tests

on:
    push:
        branches:
            - main

jobs:
    test_job:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ./jobsearch/tests/
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                pip install --user django
                
            - name: Run App Tests
              run: |
                python manage.py test


