name: JobexchangeApp Tests

on:
    push:
        branches:
            - main

jobs:
    test_job:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                pip3 install -r requirements.txt
                
            - name: Run App Tests
              run: |
                python3 manage.py test


