name: JobexchangeApp Tests

on:
    pull_request:
        branches:
            - main

jobs:
    test_job:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: ./jobsearch/tests/

        strategy:
            matrix:
                python-version: [3.10]

        steps:
            - uses: actions/checkout@v4
            
            - name: Python setup
              uses: actions/setup-python@v3
              with: 
                python-version: ${{ matrix.python-version }}
            
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r .../requirements.txt
                pip install django

            - name: Run App Tests
              run: |
                python .../manage.py test


